#import "template.typ": *

#songbook(
  title:"Duhový Zpěvník",
  subtitle: "2024",
  author: "Duha AZ",
  songs: (
    "../songs/andel.xml",
    "../songs/baroko.xml",
    "../songs/batalion.xml",
    "../songs/supermusic/bedna_vod_whisky.xml",
    "../songs/supermusic/blaznova_ukolebavka.xml",
    "../songs/supermusic/carodejnice_z_amesbury.xml",
    "../songs/supermusic/dej_mi_vic_sve_lasky.xml",
    "../songs/supermusic/dokud_sa_zpiva.xml",
    "../songs/supermusic/hlidac_krav.xml",
    "../songs/supermusic/ho_ho_watanay.xml",
    "../songs/supermusic/holubi_dum.xml",
    "../songs/supermusic/hvezdar.xml",
    "../songs/supermusic/jeste_jedno_kafe.xml",
    "../songs/kozel.xml",
    "../songs/lokomotiva.xml",
    "../songs/magdalena.xml",
    "../songs/supermusic/maracaibo.xml",
    "../songs/morituri_te_salutant.xml",
    "../songs/supermusic/nad_stadem_koni.xml",
    "../songs/rada_se_miluje.xml",
    "../songs/saro.xml",
    "../songs/severni_vitr.xml",
    "../songs/slavici_z_madridu.xml",
    "../songs/supermusic/tri_krize.xml",
    "../songs/supermusic/vsech_vandraku_muza.xml",
    "../songs/supermusic/zafukane.xml",
  )
)