#import "template.typ": *

#songbook(
  title:"Duhový Zpěvník",
  subtitle: "2024",
  author: "Duha AZ",
  songs: (
    "songs/_pouzite/1_signalni.xml",
    "songs/_pouzite/andel.xml",
    "songs/_pouzite/andele.xml",
    "songs/_pouzite/baroko.xml",
    "songs/_pouzite/batalion.xml",
    "songs/_pouzite/bedna_vod_whisky.xml",
    "songs/_pouzite/blaznova_ukolebavka.xml",
    "songs/_pouzite/buraky.xml",
    "songs/_pouzite/carodejnice_z_amesbury.xml",
    "songs/_pouzite/colorado.xml",
    "songs/_pouzite/dej_mi_vic_sve_lasky.xml",
    "songs/_pouzite/dokud_sa_zpiva.xml",
    "songs/_pouzite/frankey_dlouhan.xml",
    "songs/_pouzite/hlidac_krav.xml",
    "songs/_pouzite/ho_ho_watanay.xml",
    "songs/_pouzite/holubi_dum.xml",
    "songs/_pouzite/horely_padaly_hvezdy.xml",
    "songs/_pouzite/hruska.xml",
    "songs/_pouzite/hvezdar.xml",
    "songs/_pouzite/jdou_po_mne_jdou.xml",
    "songs/_pouzite/jednou_mi_fotr_povida.xml",
    "songs/_pouzite/jehnedy.xml",
    "songs/_pouzite/jozin_z_bazin.xml",
    "songs/_pouzite/kdyby_tady_byla_takova_panenka.xml",
    "songs/_pouzite/kometa.xml",
    "songs/_pouzite/kozel.xml",
    "songs/_pouzite/kurtizana.xml",
    "songs/_pouzite/letni_romance.xml",
    "songs/_pouzite/lokomotiva.xml",
    "songs/_pouzite/magdalena.xml",
    "songs/_pouzite/malovani.xml",
    "songs/_pouzite/maracaibo.xml",
    "songs/_pouzite/mezi_horami.xml",
    "songs/_pouzite/morituri_te_salutant.xml",
    "songs/_pouzite/mravenci_ukolebavka.xml",
    "songs/_pouzite/na_kolena.xml",
    "songs/_pouzite/na_sever.xml",
    "songs/_pouzite/na_spanelskych_schodech.xml",
    "songs/_pouzite/nad_stadem_koni.xml",
    "songs/_pouzite/napojen.xml",
    "songs/_pouzite/obluda.xml",
    "songs/_pouzite/okor.xml",
    "songs/_pouzite/otevrena_zlomenina_srdecniho_svalu.xml",
    "songs/_pouzite/pocity.xml",
    "songs/_pouzite/promeny.xml",
    "songs/_pouzite/saro.xml",
    "songs/_pouzite/sen.xml",
    "songs/_pouzite/severni_vitr.xml",
    "songs/_pouzite/sila_starejch_vin.xml",
    "songs/_pouzite/slavici_z_madridu.xml",
    "songs/_pouzite/smutecni_marse.xml",
    "songs/_pouzite/srdce_jako_knize_rohan.xml",
    "songs/_pouzite/stanky.xml",
    "songs/_pouzite/tereza.xml",
    "songs/_pouzite/tri_krize.xml",
    "songs/_pouzite/uz_to_nenapravim.xml",
    "songs/_pouzite/vizovice.xml",
    "songs/_pouzite/vsech_vandraku_muza.xml",
    "songs/_pouzite/zafukane.xml",
    "songs/_pouzite/zelene_francouzske_plane.xml",
    "songs/_pouzite/zelva.xml",
    "songs/_pouzite/az.xml",
    "songs/_pouzite/klidna_jako_voda.xml",
    "songs/_pouzite/dva_havrani.xml",
    "songs/_pouzite/huslicky.xml",
    "songs/_pouzite/pramen_zdravi_z_posazavi.xml",
    "songs/_pouzite/tri_citronky.xml",
    "songs/_pouzite/hospoda.xml",
    // "songs/_pouzite/jeste_jedno_kafe.xml",
    // "songs/_pouzite/rada_se_miluje.xml",
  )
)