#import "template.typ": *

#songbook(
  title:"Duhový Zpěvník",
  subtitle: "2024",
  author: "Duha AZ",
  songs: (
    "songs/_pouzite/andel.xml",
    "songs/_pouzite/baroko.xml",
    "songs/_pouzite/batalion.xml",
    "songs/_pouzite/bedna_vod_whisky.xml",
    "songs/_pouzite/blaznova_ukolebavka.xml",
    "songs/_pouzite/carodejnice_z_amesbury.xml",
    "songs/_pouzite/dej_mi_vic_sve_lasky.xml",
    "songs/_pouzite/dokud_sa_zpiva.xml",
    "songs/_pouzite/hlidac_krav.xml",
    "songs/_pouzite/ho_ho_watanay.xml",
    "songs/_pouzite/holubi_dum.xml",
    "songs/_pouzite/hvezdar.xml",
    "songs/_pouzite/jeste_jedno_kafe.xml",
    "songs/_pouzite/kozel.xml",
    "songs/_pouzite/lokomotiva.xml",
    "songs/_pouzite/magdalena.xml",
    "songs/_pouzite/maracaibo.xml",
    "songs/_pouzite/morituri_te_salutant.xml",
    "songs/_pouzite/nad_stadem_koni.xml",
    "songs/_pouzite/rada_se_miluje.xml",
    "songs/_pouzite/saro.xml",
    "songs/_pouzite/severni_vitr.xml",
    "songs/_pouzite/slavici_z_madridu.xml",
    "songs/_pouzite/tri_krize.xml",
    "songs/_pouzite/vsech_vandraku_muza.xml",
    "songs/_pouzite/zafukane.xml",

    "songs/_pouzite/nove/1_signalni.xml",
    "songs/_pouzite/nove/andele.xml",
    "songs/_pouzite/nove/buraky.xml",
    "songs/_pouzite/nove/colorado.xml",
    "songs/_pouzite/nove/frankey_dlouhan.xml",
    "songs/_pouzite/nove/horely_padaly_hvezdy.xml",
    "songs/_pouzite/nove/hruska.xml",
    "songs/_pouzite/nove/jdou_po_mne_jdou.xml",
    "songs/_pouzite/nove/jednou_mi_fotr_povida.xml",
    "songs/_pouzite/nove/jehnedy.xml",
    "songs/_pouzite/nove/jozin_z_bazin.xml",
    "songs/_pouzite/nove/kdyby_tady_byla_takova_panenka.xml",
    "songs/_pouzite/nove/kometa.xml",
    "songs/_pouzite/nove/kurtizana.xml",
    "songs/_pouzite/nove/letni_romance.xml",
    "songs/_pouzite/nove/malovani.xml",
    "songs/_pouzite/nove/mezi_horami.xml",
    "songs/_pouzite/nove/mravenci_ukolebavka.xml",
    "songs/_pouzite/nove/napojen.xml",
    "songs/_pouzite/nove/obluda.xml",
    "songs/_pouzite/nove/okor.xml",
    "songs/_pouzite/nove/otevrena_zlomenina_srdecniho_svalu.xml",
    "songs/_pouzite/nove/pocity.xml",
    "songs/_pouzite/nove/promeny.xml",
    "songs/_pouzite/nove/sen.xml",
    "songs/_pouzite/nove/sila_starejch_vin.xml",
    "songs/_pouzite/nove/smutecni_marse.xml",
    "songs/_pouzite/nove/srdce_jako_knize_rohan.xml",
    "songs/_pouzite/nove/stanky.xml",
    "songs/_pouzite/nove/tereza.xml",
    "songs/_pouzite/nove/uz_to_nenapravim.xml",
    "songs/_pouzite/nove/vizovice.xml",
    "songs/_pouzite/nove/zelene_francouzske_plane.xml",
    "songs/_pouzite/nove/zelva.xml",
  )
)